package com.register.serviceRF.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.register.serviceRF.model.AreaSownField;
import com.register.serviceRF.service.AreaSownFieldService;
import com.register.serviceRF.service.persistence.AreaPersistence;
import com.register.serviceRF.service.persistence.AreaSownFieldPersistence;
import com.register.serviceRF.service.persistence.FarmerFinder;
import com.register.serviceRF.service.persistence.FarmerPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the area sown field remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.register.serviceRF.service.impl.AreaSownFieldServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.register.serviceRF.service.impl.AreaSownFieldServiceImpl
 * @see com.register.serviceRF.service.AreaSownFieldServiceUtil
 * @generated
 */
public abstract class AreaSownFieldServiceBaseImpl extends BaseServiceImpl
    implements AreaSownFieldService, IdentifiableBean {
    @BeanReference(type = com.register.serviceRF.service.AreaLocalService.class)
    protected com.register.serviceRF.service.AreaLocalService areaLocalService;
    @BeanReference(type = com.register.serviceRF.service.AreaService.class)
    protected com.register.serviceRF.service.AreaService areaService;
    @BeanReference(type = AreaPersistence.class)
    protected AreaPersistence areaPersistence;
    @BeanReference(type = com.register.serviceRF.service.AreaSownFieldLocalService.class)
    protected com.register.serviceRF.service.AreaSownFieldLocalService areaSownFieldLocalService;
    @BeanReference(type = com.register.serviceRF.service.AreaSownFieldService.class)
    protected com.register.serviceRF.service.AreaSownFieldService areaSownFieldService;
    @BeanReference(type = AreaSownFieldPersistence.class)
    protected AreaSownFieldPersistence areaSownFieldPersistence;
    @BeanReference(type = com.register.serviceRF.service.FarmerLocalService.class)
    protected com.register.serviceRF.service.FarmerLocalService farmerLocalService;
    @BeanReference(type = com.register.serviceRF.service.FarmerService.class)
    protected com.register.serviceRF.service.FarmerService farmerService;
    @BeanReference(type = FarmerPersistence.class)
    protected FarmerPersistence farmerPersistence;
    @BeanReference(type = FarmerFinder.class)
    protected FarmerFinder farmerFinder;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private AreaSownFieldServiceClpInvoker _clpInvoker = new AreaSownFieldServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.register.serviceRF.service.AreaSownFieldServiceUtil} to access the area sown field remote service.
     */

    /**
     * Returns the area local service.
     *
     * @return the area local service
     */
    public com.register.serviceRF.service.AreaLocalService getAreaLocalService() {
        return areaLocalService;
    }

    /**
     * Sets the area local service.
     *
     * @param areaLocalService the area local service
     */
    public void setAreaLocalService(
        com.register.serviceRF.service.AreaLocalService areaLocalService) {
        this.areaLocalService = areaLocalService;
    }

    /**
     * Returns the area remote service.
     *
     * @return the area remote service
     */
    public com.register.serviceRF.service.AreaService getAreaService() {
        return areaService;
    }

    /**
     * Sets the area remote service.
     *
     * @param areaService the area remote service
     */
    public void setAreaService(
        com.register.serviceRF.service.AreaService areaService) {
        this.areaService = areaService;
    }

    /**
     * Returns the area persistence.
     *
     * @return the area persistence
     */
    public AreaPersistence getAreaPersistence() {
        return areaPersistence;
    }

    /**
     * Sets the area persistence.
     *
     * @param areaPersistence the area persistence
     */
    public void setAreaPersistence(AreaPersistence areaPersistence) {
        this.areaPersistence = areaPersistence;
    }

    /**
     * Returns the area sown field local service.
     *
     * @return the area sown field local service
     */
    public com.register.serviceRF.service.AreaSownFieldLocalService getAreaSownFieldLocalService() {
        return areaSownFieldLocalService;
    }

    /**
     * Sets the area sown field local service.
     *
     * @param areaSownFieldLocalService the area sown field local service
     */
    public void setAreaSownFieldLocalService(
        com.register.serviceRF.service.AreaSownFieldLocalService areaSownFieldLocalService) {
        this.areaSownFieldLocalService = areaSownFieldLocalService;
    }

    /**
     * Returns the area sown field remote service.
     *
     * @return the area sown field remote service
     */
    public com.register.serviceRF.service.AreaSownFieldService getAreaSownFieldService() {
        return areaSownFieldService;
    }

    /**
     * Sets the area sown field remote service.
     *
     * @param areaSownFieldService the area sown field remote service
     */
    public void setAreaSownFieldService(
        com.register.serviceRF.service.AreaSownFieldService areaSownFieldService) {
        this.areaSownFieldService = areaSownFieldService;
    }

    /**
     * Returns the area sown field persistence.
     *
     * @return the area sown field persistence
     */
    public AreaSownFieldPersistence getAreaSownFieldPersistence() {
        return areaSownFieldPersistence;
    }

    /**
     * Sets the area sown field persistence.
     *
     * @param areaSownFieldPersistence the area sown field persistence
     */
    public void setAreaSownFieldPersistence(
        AreaSownFieldPersistence areaSownFieldPersistence) {
        this.areaSownFieldPersistence = areaSownFieldPersistence;
    }

    /**
     * Returns the farmer local service.
     *
     * @return the farmer local service
     */
    public com.register.serviceRF.service.FarmerLocalService getFarmerLocalService() {
        return farmerLocalService;
    }

    /**
     * Sets the farmer local service.
     *
     * @param farmerLocalService the farmer local service
     */
    public void setFarmerLocalService(
        com.register.serviceRF.service.FarmerLocalService farmerLocalService) {
        this.farmerLocalService = farmerLocalService;
    }

    /**
     * Returns the farmer remote service.
     *
     * @return the farmer remote service
     */
    public com.register.serviceRF.service.FarmerService getFarmerService() {
        return farmerService;
    }

    /**
     * Sets the farmer remote service.
     *
     * @param farmerService the farmer remote service
     */
    public void setFarmerService(
        com.register.serviceRF.service.FarmerService farmerService) {
        this.farmerService = farmerService;
    }

    /**
     * Returns the farmer persistence.
     *
     * @return the farmer persistence
     */
    public FarmerPersistence getFarmerPersistence() {
        return farmerPersistence;
    }

    /**
     * Sets the farmer persistence.
     *
     * @param farmerPersistence the farmer persistence
     */
    public void setFarmerPersistence(FarmerPersistence farmerPersistence) {
        this.farmerPersistence = farmerPersistence;
    }

    /**
     * Returns the farmer finder.
     *
     * @return the farmer finder
     */
    public FarmerFinder getFarmerFinder() {
        return farmerFinder;
    }

    /**
     * Sets the farmer finder.
     *
     * @param farmerFinder the farmer finder
     */
    public void setFarmerFinder(FarmerFinder farmerFinder) {
        this.farmerFinder = farmerFinder;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return AreaSownField.class;
    }

    protected String getModelClassName() {
        return AreaSownField.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = areaSownFieldPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
