package com.register.serviceRF.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.register.serviceRF.model.Area;
import com.register.serviceRF.service.AreaLocalService;
import com.register.serviceRF.service.persistence.AreaPersistence;
import com.register.serviceRF.service.persistence.AreaSownFieldPersistence;
import com.register.serviceRF.service.persistence.FarmerFinder;
import com.register.serviceRF.service.persistence.FarmerPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the area local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.register.serviceRF.service.impl.AreaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.register.serviceRF.service.impl.AreaLocalServiceImpl
 * @see com.register.serviceRF.service.AreaLocalServiceUtil
 * @generated
 */
public abstract class AreaLocalServiceBaseImpl extends BaseLocalServiceImpl
    implements AreaLocalService, IdentifiableBean {
    @BeanReference(type = com.register.serviceRF.service.AreaLocalService.class)
    protected com.register.serviceRF.service.AreaLocalService areaLocalService;
    @BeanReference(type = com.register.serviceRF.service.AreaService.class)
    protected com.register.serviceRF.service.AreaService areaService;
    @BeanReference(type = AreaPersistence.class)
    protected AreaPersistence areaPersistence;
    @BeanReference(type = com.register.serviceRF.service.AreaSownFieldLocalService.class)
    protected com.register.serviceRF.service.AreaSownFieldLocalService areaSownFieldLocalService;
    @BeanReference(type = com.register.serviceRF.service.AreaSownFieldService.class)
    protected com.register.serviceRF.service.AreaSownFieldService areaSownFieldService;
    @BeanReference(type = AreaSownFieldPersistence.class)
    protected AreaSownFieldPersistence areaSownFieldPersistence;
    @BeanReference(type = com.register.serviceRF.service.FarmerLocalService.class)
    protected com.register.serviceRF.service.FarmerLocalService farmerLocalService;
    @BeanReference(type = com.register.serviceRF.service.FarmerService.class)
    protected com.register.serviceRF.service.FarmerService farmerService;
    @BeanReference(type = FarmerPersistence.class)
    protected FarmerPersistence farmerPersistence;
    @BeanReference(type = FarmerFinder.class)
    protected FarmerFinder farmerFinder;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private AreaLocalServiceClpInvoker _clpInvoker = new AreaLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.register.serviceRF.service.AreaLocalServiceUtil} to access the area local service.
     */

    /**
     * Adds the area to the database. Also notifies the appropriate model listeners.
     *
     * @param area the area
     * @return the area that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public Area addArea(Area area) throws SystemException {
        area.setNew(true);

        return areaPersistence.update(area);
    }

    /**
     * Creates a new area with the primary key. Does not add the area to the database.
     *
     * @param areaId the primary key for the new area
     * @return the new area
     */
    @Override
    public Area createArea(long areaId) {
        return areaPersistence.create(areaId);
    }

    /**
     * Deletes the area with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param areaId the primary key of the area
     * @return the area that was removed
     * @throws PortalException if a area with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public Area deleteArea(long areaId) throws PortalException, SystemException {
        return areaPersistence.remove(areaId);
    }

    /**
     * Deletes the area from the database. Also notifies the appropriate model listeners.
     *
     * @param area the area
     * @return the area that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public Area deleteArea(Area area) throws SystemException {
        return areaPersistence.remove(area);
    }

    @Override
    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(Area.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return areaPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.register.serviceRF.model.impl.AreaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return areaPersistence.findWithDynamicQuery(dynamicQuery, start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.register.serviceRF.model.impl.AreaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return areaPersistence.findWithDynamicQuery(dynamicQuery, start, end,
            orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return areaPersistence.countWithDynamicQuery(dynamicQuery);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @param projection the projection to apply to the query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery,
        Projection projection) throws SystemException {
        return areaPersistence.countWithDynamicQuery(dynamicQuery, projection);
    }

    @Override
    public Area fetchArea(long areaId) throws SystemException {
        return areaPersistence.fetchByPrimaryKey(areaId);
    }

    /**
     * Returns the area with the matching UUID and company.
     *
     * @param uuid the area's UUID
     * @param  companyId the primary key of the company
     * @return the matching area, or <code>null</code> if a matching area could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public Area fetchAreaByUuidAndCompanyId(String uuid, long companyId)
        throws SystemException {
        return areaPersistence.fetchByUuid_C_First(uuid, companyId, null);
    }

    /**
     * Returns the area matching the UUID and group.
     *
     * @param uuid the area's UUID
     * @param groupId the primary key of the group
     * @return the matching area, or <code>null</code> if a matching area could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public Area fetchAreaByUuidAndGroupId(String uuid, long groupId)
        throws SystemException {
        return areaPersistence.fetchByUUID_G(uuid, groupId);
    }

    /**
     * Returns the area with the primary key.
     *
     * @param areaId the primary key of the area
     * @return the area
     * @throws PortalException if a area with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public Area getArea(long areaId) throws PortalException, SystemException {
        return areaPersistence.findByPrimaryKey(areaId);
    }

    @Override
    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return areaPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns the area with the matching UUID and company.
     *
     * @param uuid the area's UUID
     * @param  companyId the primary key of the company
     * @return the matching area
     * @throws PortalException if a matching area could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public Area getAreaByUuidAndCompanyId(String uuid, long companyId)
        throws PortalException, SystemException {
        return areaPersistence.findByUuid_C_First(uuid, companyId, null);
    }

    /**
     * Returns the area matching the UUID and group.
     *
     * @param uuid the area's UUID
     * @param groupId the primary key of the group
     * @return the matching area
     * @throws PortalException if a matching area could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public Area getAreaByUuidAndGroupId(String uuid, long groupId)
        throws PortalException, SystemException {
        return areaPersistence.findByUUID_G(uuid, groupId);
    }

    /**
     * Returns a range of all the areas.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.register.serviceRF.model.impl.AreaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param start the lower bound of the range of areas
     * @param end the upper bound of the range of areas (not inclusive)
     * @return the range of areas
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<Area> getAreas(int start, int end) throws SystemException {
        return areaPersistence.findAll(start, end);
    }

    /**
     * Returns the number of areas.
     *
     * @return the number of areas
     * @throws SystemException if a system exception occurred
     */
    @Override
    public int getAreasCount() throws SystemException {
        return areaPersistence.countAll();
    }

    /**
     * Updates the area in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param area the area
     * @return the area that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public Area updateArea(Area area) throws SystemException {
        return areaPersistence.update(area);
    }

    /**
     * Returns the area local service.
     *
     * @return the area local service
     */
    public com.register.serviceRF.service.AreaLocalService getAreaLocalService() {
        return areaLocalService;
    }

    /**
     * Sets the area local service.
     *
     * @param areaLocalService the area local service
     */
    public void setAreaLocalService(
        com.register.serviceRF.service.AreaLocalService areaLocalService) {
        this.areaLocalService = areaLocalService;
    }

    /**
     * Returns the area remote service.
     *
     * @return the area remote service
     */
    public com.register.serviceRF.service.AreaService getAreaService() {
        return areaService;
    }

    /**
     * Sets the area remote service.
     *
     * @param areaService the area remote service
     */
    public void setAreaService(
        com.register.serviceRF.service.AreaService areaService) {
        this.areaService = areaService;
    }

    /**
     * Returns the area persistence.
     *
     * @return the area persistence
     */
    public AreaPersistence getAreaPersistence() {
        return areaPersistence;
    }

    /**
     * Sets the area persistence.
     *
     * @param areaPersistence the area persistence
     */
    public void setAreaPersistence(AreaPersistence areaPersistence) {
        this.areaPersistence = areaPersistence;
    }

    /**
     * Returns the area sown field local service.
     *
     * @return the area sown field local service
     */
    public com.register.serviceRF.service.AreaSownFieldLocalService getAreaSownFieldLocalService() {
        return areaSownFieldLocalService;
    }

    /**
     * Sets the area sown field local service.
     *
     * @param areaSownFieldLocalService the area sown field local service
     */
    public void setAreaSownFieldLocalService(
        com.register.serviceRF.service.AreaSownFieldLocalService areaSownFieldLocalService) {
        this.areaSownFieldLocalService = areaSownFieldLocalService;
    }

    /**
     * Returns the area sown field remote service.
     *
     * @return the area sown field remote service
     */
    public com.register.serviceRF.service.AreaSownFieldService getAreaSownFieldService() {
        return areaSownFieldService;
    }

    /**
     * Sets the area sown field remote service.
     *
     * @param areaSownFieldService the area sown field remote service
     */
    public void setAreaSownFieldService(
        com.register.serviceRF.service.AreaSownFieldService areaSownFieldService) {
        this.areaSownFieldService = areaSownFieldService;
    }

    /**
     * Returns the area sown field persistence.
     *
     * @return the area sown field persistence
     */
    public AreaSownFieldPersistence getAreaSownFieldPersistence() {
        return areaSownFieldPersistence;
    }

    /**
     * Sets the area sown field persistence.
     *
     * @param areaSownFieldPersistence the area sown field persistence
     */
    public void setAreaSownFieldPersistence(
        AreaSownFieldPersistence areaSownFieldPersistence) {
        this.areaSownFieldPersistence = areaSownFieldPersistence;
    }

    /**
     * Returns the farmer local service.
     *
     * @return the farmer local service
     */
    public com.register.serviceRF.service.FarmerLocalService getFarmerLocalService() {
        return farmerLocalService;
    }

    /**
     * Sets the farmer local service.
     *
     * @param farmerLocalService the farmer local service
     */
    public void setFarmerLocalService(
        com.register.serviceRF.service.FarmerLocalService farmerLocalService) {
        this.farmerLocalService = farmerLocalService;
    }

    /**
     * Returns the farmer remote service.
     *
     * @return the farmer remote service
     */
    public com.register.serviceRF.service.FarmerService getFarmerService() {
        return farmerService;
    }

    /**
     * Sets the farmer remote service.
     *
     * @param farmerService the farmer remote service
     */
    public void setFarmerService(
        com.register.serviceRF.service.FarmerService farmerService) {
        this.farmerService = farmerService;
    }

    /**
     * Returns the farmer persistence.
     *
     * @return the farmer persistence
     */
    public FarmerPersistence getFarmerPersistence() {
        return farmerPersistence;
    }

    /**
     * Sets the farmer persistence.
     *
     * @param farmerPersistence the farmer persistence
     */
    public void setFarmerPersistence(FarmerPersistence farmerPersistence) {
        this.farmerPersistence = farmerPersistence;
    }

    /**
     * Returns the farmer finder.
     *
     * @return the farmer finder
     */
    public FarmerFinder getFarmerFinder() {
        return farmerFinder;
    }

    /**
     * Sets the farmer finder.
     *
     * @param farmerFinder the farmer finder
     */
    public void setFarmerFinder(FarmerFinder farmerFinder) {
        this.farmerFinder = farmerFinder;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("com.register.serviceRF.model.Area",
            areaLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.register.serviceRF.model.Area");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Area.class;
    }

    protected String getModelClassName() {
        return Area.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = areaPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
