package com.register.serviceRF.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AreaSownField service. Represents a row in the &quot;RF_AreaSownField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.register.serviceRF.model.impl.AreaSownFieldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.register.serviceRF.model.impl.AreaSownFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AreaSownField
 * @see com.register.serviceRF.model.impl.AreaSownFieldImpl
 * @see com.register.serviceRF.model.impl.AreaSownFieldModelImpl
 * @generated
 */
public interface AreaSownFieldModel extends BaseModel<AreaSownField>,
    StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a area sown field model instance should use the {@link AreaSownField} interface instead.
     */

    /**
     * Returns the primary key of this area sown field.
     *
     * @return the primary key of this area sown field
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this area sown field.
     *
     * @param primaryKey the primary key of this area sown field
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this area sown field.
     *
     * @return the uuid of this area sown field
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this area sown field.
     *
     * @param uuid the uuid of this area sown field
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the area sown fields ID of this area sown field.
     *
     * @return the area sown fields ID of this area sown field
     */
    public long getAreaSownFieldsId();

    /**
     * Sets the area sown fields ID of this area sown field.
     *
     * @param areaSownFieldsId the area sown fields ID of this area sown field
     */
    public void setAreaSownFieldsId(long areaSownFieldsId);

    /**
     * Returns the group ID of this area sown field.
     *
     * @return the group ID of this area sown field
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this area sown field.
     *
     * @param groupId the group ID of this area sown field
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this area sown field.
     *
     * @return the company ID of this area sown field
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this area sown field.
     *
     * @param companyId the company ID of this area sown field
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this area sown field.
     *
     * @return the user ID of this area sown field
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this area sown field.
     *
     * @param userId the user ID of this area sown field
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this area sown field.
     *
     * @return the user uuid of this area sown field
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this area sown field.
     *
     * @param userUuid the user uuid of this area sown field
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this area sown field.
     *
     * @return the user name of this area sown field
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this area sown field.
     *
     * @param userName the user name of this area sown field
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this area sown field.
     *
     * @return the create date of this area sown field
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this area sown field.
     *
     * @param createDate the create date of this area sown field
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this area sown field.
     *
     * @return the modified date of this area sown field
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this area sown field.
     *
     * @param modifiedDate the modified date of this area sown field
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the farmer ID of this area sown field.
     *
     * @return the farmer ID of this area sown field
     */
    public long getFarmerId();

    /**
     * Sets the farmer ID of this area sown field.
     *
     * @param farmerId the farmer ID of this area sown field
     */
    public void setFarmerId(long farmerId);

    /**
     * Returns the area ID of this area sown field.
     *
     * @return the area ID of this area sown field
     */
    public long getAreaId();

    /**
     * Sets the area ID of this area sown field.
     *
     * @param areaId the area ID of this area sown field
     */
    public void setAreaId(long areaId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.register.serviceRF.model.AreaSownField areaSownField);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.register.serviceRF.model.AreaSownField> toCacheModel();

    @Override
    public com.register.serviceRF.model.AreaSownField toEscapedModel();

    @Override
    public com.register.serviceRF.model.AreaSownField toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
