package com.register.serviceRF.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Area service. Represents a row in the &quot;RF_Area&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.register.serviceRF.model.impl.AreaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.register.serviceRF.model.impl.AreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Area
 * @see com.register.serviceRF.model.impl.AreaImpl
 * @see com.register.serviceRF.model.impl.AreaModelImpl
 * @generated
 */
public interface AreaModel extends BaseModel<Area>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a area model instance should use the {@link Area} interface instead.
     */

    /**
     * Returns the primary key of this area.
     *
     * @return the primary key of this area
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this area.
     *
     * @param primaryKey the primary key of this area
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this area.
     *
     * @return the uuid of this area
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this area.
     *
     * @param uuid the uuid of this area
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the area ID of this area.
     *
     * @return the area ID of this area
     */
    public long getAreaId();

    /**
     * Sets the area ID of this area.
     *
     * @param areaId the area ID of this area
     */
    public void setAreaId(long areaId);

    /**
     * Returns the group ID of this area.
     *
     * @return the group ID of this area
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this area.
     *
     * @param groupId the group ID of this area
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this area.
     *
     * @return the company ID of this area
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this area.
     *
     * @param companyId the company ID of this area
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this area.
     *
     * @return the user ID of this area
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this area.
     *
     * @param userId the user ID of this area
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this area.
     *
     * @return the user uuid of this area
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this area.
     *
     * @param userUuid the user uuid of this area
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this area.
     *
     * @return the user name of this area
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this area.
     *
     * @param userName the user name of this area
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this area.
     *
     * @return the create date of this area
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this area.
     *
     * @param createDate the create date of this area
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this area.
     *
     * @return the modified date of this area
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this area.
     *
     * @param modifiedDate the modified date of this area
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the title of this area.
     *
     * @return the title of this area
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this area.
     *
     * @param title the title of this area
     */
    public void setTitle(String title);

    /**
     * Returns the area code of this area.
     *
     * @return the area code of this area
     */
    public long getAreaCode();

    /**
     * Sets the area code of this area.
     *
     * @param areaCode the area code of this area
     */
    public void setAreaCode(long areaCode);

    /**
     * Returns the in archive of this area.
     *
     * @return the in archive of this area
     */
    public boolean getInArchive();

    /**
     * Returns <code>true</code> if this area is in archive.
     *
     * @return <code>true</code> if this area is in archive; <code>false</code> otherwise
     */
    public boolean isInArchive();

    /**
     * Sets whether this area is in archive.
     *
     * @param inArchive the in archive of this area
     */
    public void setInArchive(boolean inArchive);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.register.serviceRF.model.Area area);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.register.serviceRF.model.Area> toCacheModel();

    @Override
    public com.register.serviceRF.model.Area toEscapedModel();

    @Override
    public com.register.serviceRF.model.Area toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
