package com.register.serviceRF.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Farmer service. Represents a row in the &quot;RF_Farmer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.register.serviceRF.model.impl.FarmerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.register.serviceRF.model.impl.FarmerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Farmer
 * @see com.register.serviceRF.model.impl.FarmerImpl
 * @see com.register.serviceRF.model.impl.FarmerModelImpl
 * @generated
 */
public interface FarmerModel extends BaseModel<Farmer>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a farmer model instance should use the {@link Farmer} interface instead.
     */

    /**
     * Returns the primary key of this farmer.
     *
     * @return the primary key of this farmer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this farmer.
     *
     * @param primaryKey the primary key of this farmer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this farmer.
     *
     * @return the uuid of this farmer
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this farmer.
     *
     * @param uuid the uuid of this farmer
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the farmer ID of this farmer.
     *
     * @return the farmer ID of this farmer
     */
    public long getFarmerId();

    /**
     * Sets the farmer ID of this farmer.
     *
     * @param farmerId the farmer ID of this farmer
     */
    public void setFarmerId(long farmerId);

    /**
     * Returns the group ID of this farmer.
     *
     * @return the group ID of this farmer
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this farmer.
     *
     * @param groupId the group ID of this farmer
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this farmer.
     *
     * @return the company ID of this farmer
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this farmer.
     *
     * @param companyId the company ID of this farmer
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this farmer.
     *
     * @return the user ID of this farmer
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this farmer.
     *
     * @param userId the user ID of this farmer
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this farmer.
     *
     * @return the user uuid of this farmer
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this farmer.
     *
     * @param userUuid the user uuid of this farmer
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this farmer.
     *
     * @return the user name of this farmer
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this farmer.
     *
     * @param userName the user name of this farmer
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this farmer.
     *
     * @return the create date of this farmer
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this farmer.
     *
     * @param createDate the create date of this farmer
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this farmer.
     *
     * @return the modified date of this farmer
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this farmer.
     *
     * @param modifiedDate the modified date of this farmer
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name organization of this farmer.
     *
     * @return the name organization of this farmer
     */
    @AutoEscape
    public String getNameOrganization();

    /**
     * Sets the name organization of this farmer.
     *
     * @param nameOrganization the name organization of this farmer
     */
    public void setNameOrganization(String nameOrganization);

    /**
     * Returns the organizational legal form of this farmer.
     *
     * @return the organizational legal form of this farmer
     */
    @AutoEscape
    public String getOrganizationalLegalForm();

    /**
     * Sets the organizational legal form of this farmer.
     *
     * @param organizationalLegalForm the organizational legal form of this farmer
     */
    public void setOrganizationalLegalForm(String organizationalLegalForm);

    /**
     * Returns the i n n of this farmer.
     *
     * @return the i n n of this farmer
     */
    public long getINN();

    /**
     * Sets the i n n of this farmer.
     *
     * @param INN the i n n of this farmer
     */
    public void setINN(long INN);

    /**
     * Returns the k p p of this farmer.
     *
     * @return the k p p of this farmer
     */
    public long getKPP();

    /**
     * Sets the k p p of this farmer.
     *
     * @param KPP the k p p of this farmer
     */
    public void setKPP(long KPP);

    /**
     * Returns the o g r n of this farmer.
     *
     * @return the o g r n of this farmer
     */
    public long getOGRN();

    /**
     * Sets the o g r n of this farmer.
     *
     * @param OGRN the o g r n of this farmer
     */
    public void setOGRN(long OGRN);

    /**
     * Returns the registration area of this farmer.
     *
     * @return the registration area of this farmer
     */
    @AutoEscape
    public String getRegistrationArea();

    /**
     * Sets the registration area of this farmer.
     *
     * @param registrationArea the registration area of this farmer
     */
    public void setRegistrationArea(String registrationArea);

    /**
     * Returns the areas sown fields of this farmer.
     *
     * @return the areas sown fields of this farmer
     */
    @AutoEscape
    public String getAreasSownFields();

    /**
     * Sets the areas sown fields of this farmer.
     *
     * @param areasSownFields the areas sown fields of this farmer
     */
    public void setAreasSownFields(String areasSownFields);

    /**
     * Returns the registration date of this farmer.
     *
     * @return the registration date of this farmer
     */
    public Date getRegistrationDate();

    /**
     * Sets the registration date of this farmer.
     *
     * @param registrationDate the registration date of this farmer
     */
    public void setRegistrationDate(Date registrationDate);

    /**
     * Returns the in archive of this farmer.
     *
     * @return the in archive of this farmer
     */
    public boolean getInArchive();

    /**
     * Returns <code>true</code> if this farmer is in archive.
     *
     * @return <code>true</code> if this farmer is in archive; <code>false</code> otherwise
     */
    public boolean isInArchive();

    /**
     * Sets whether this farmer is in archive.
     *
     * @param inArchive the in archive of this farmer
     */
    public void setInArchive(boolean inArchive);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.register.serviceRF.model.Farmer farmer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.register.serviceRF.model.Farmer> toCacheModel();

    @Override
    public com.register.serviceRF.model.Farmer toEscapedModel();

    @Override
    public com.register.serviceRF.model.Farmer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
