package com.register.serviceRF.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.register.serviceRF.model.AreaSownField;
import com.register.serviceRF.service.AreaSownFieldLocalServiceUtil;

/**
 * The extended model base implementation for the AreaSownField service. Represents a row in the &quot;RF_AreaSownField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AreaSownFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AreaSownFieldImpl
 * @see com.register.serviceRF.model.AreaSownField
 * @generated
 */
public abstract class AreaSownFieldBaseImpl extends AreaSownFieldModelImpl
    implements AreaSownField {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a area sown field model instance should use the {@link AreaSownField} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AreaSownFieldLocalServiceUtil.addAreaSownField(this);
        } else {
            AreaSownFieldLocalServiceUtil.updateAreaSownField(this);
        }
    }
}
